trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'package'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '/home/vsts/work/1/s/target/'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'jarfile'
      publishLocation: 'Container'